#!/bin/bash

#timecode=$(date +%Y%m%d_%H%M%S)
timecode=20241119
echo $timecode
outputName="./VulkanCPD_"${timecode}".xlsx"

cpd.sh  -d "F:/vulkanengine/Engine/Source/Runtime/Vulkan,F:/zzchange/zzorg" -o ${outputName} -m "vulkanengine|zzorg"
start ${outputName}